spring:
  application:
    name: document-ai-platform
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/document_ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: MANUAL

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.davydcr.document: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  ocr:
    engine: tesseract
  ai:
    model: llama3
    baseUrl: http://localhost:11434
  async:
    processing-enabled: false
